"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.createShipmentManifest = void 0;
const functions = __importStar(require("firebase-functions/v2"));
const admin = __importStar(require("firebase-admin"));
const firestore_1 = require("firebase-admin/firestore");
const config_1 = require("./config");
exports.createShipmentManifest = functions.https.onCall({ region: 'asia-south1', enforceAppCheck: false }, async (request) => {
    var _a, _b, _c, _d, _e, _f;
    try {
        const auth = request.auth;
        if (!auth)
            throw new functions.https.HttpsError('unauthenticated', 'User must be logged in.');
        const { firestoreOrderId, vendorAddress, buyerAddress, items, totalWeight, totalAmount } = request.data;
        // Delhivery Manifest Payload structure
        const payload = {
            format: 'json',
            data: {
                shipments: [
                    {
                        waybill: '', // Delhivery will auto-generate if empty
                        reference_number: firestoreOrderId,
                        name: buyerAddress.name || 'Customer',
                        phone: buyerAddress.phone || '9999999999',
                        address: buyerAddress.addressLine,
                        pin: buyerAddress.pincode,
                        city: buyerAddress.city || 'Bangalore',
                        state: buyerAddress.state || 'Karnataka',
                        country: 'India',
                        order: firestoreOrderId,
                        order_date: new Date().toISOString(),
                        payment_mode: 'Prepaid', // Or COD depending on checkout
                        total_amount: totalAmount,
                        quantity: items.length,
                        weight: totalWeight || 1.5, // in KGs
                        products_desc: items.map((i) => i.name).join(', '),
                    }
                ],
                pickup_location: {
                    name: vendorAddress.storeName || 'Vendor Store',
                    add: vendorAddress.addressLine || 'Vendor Address',
                    city: vendorAddress.city || 'Bangalore',
                    pin_code: vendorAddress.pincode || '560102',
                    country: 'India',
                    phone: vendorAddress.phone || '8888888888'
                }
            }
        };
        // Create manifest
        const response = await config_1.delhiveryClient.post('/manifest', `format=json&data=${JSON.stringify(payload.data)}`, {
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            }
        });
        const waybill = (_b = (_a = response.data.packages) === null || _a === void 0 ? void 0 : _a[0]) === null || _b === void 0 ? void 0 : _b.waybill;
        if (!waybill) {
            throw new Error('No waybill generated by Delhivery');
        }
        // Update Firestore Order with LRN (Waybill)
        await admin.firestore().collection('orders').doc(firestoreOrderId).update({
            delhiveryWaybill: waybill,
            shippingStatus: 'manifest_created',
            updatedAt: firestore_1.FieldValue.serverTimestamp(),
        });
        return {
            success: true,
            waybill,
            message: response.data.message
        };
    }
    catch (error) {
        console.error('Delhivery Manifest Error:', ((_c = error.response) === null || _c === void 0 ? void 0 : _c.data) || error.message);
        // Fallback for demo purposes if API token is missing/invalid
        if (((_d = error.response) === null || _d === void 0 ? void 0 : _d.status) === 401 || ((_e = error.response) === null || _e === void 0 ? void 0 : _e.status) === 403 || ((_f = error.response) === null || _f === void 0 ? void 0 : _f.status) === 400 || error.code === 'ERR_BAD_REQUEST') {
            const mockWaybill = `AWB_MOCK_${Date.now()}`;
            await admin.firestore().collection('orders').doc(request.data.firestoreOrderId).update({
                delhiveryWaybill: mockWaybill,
                shippingStatus: 'manifest_created',
                isMockDelhivery: true,
                updatedAt: firestore_1.FieldValue.serverTimestamp(),
            });
            return { success: true, waybill: mockWaybill, isMock: true };
        }
        throw new functions.https.HttpsError('internal', 'Unable to create shipment manifest.');
    }
});
//# sourceMappingURL=shipmentService.js.map